# This is a basic workflow to help you get started with Actions

name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Listar arquivos
        run: ls -la

